payment.refund.minCancelHours=2

app.frontend.baseUrl=http://localhost:5173

app.backend.publicBaseUrl=
app.backend.contextPath=/backend

payment.momo.partnerCode=
payment.momo.accessKey=
payment.momo.secretKey=
payment.momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
payment.momo.returnUrl=${app.backend.publicBaseUrl}${app.backend.contextPath}/api/payments/momo/result
payment.momo.ipnUrl=${app.backend.publicBaseUrl}${app.backend.contextPath}/api/payments/momo/ipn
payment.momo.refundEndpoint=https://test-payment.momo.vn/v2/gateway/api/refund
payment.momo.query=https://test-payment.momo.vn/v2/gateway/api/query
payment.momo.frontendReturnUrl=${app.frontend.baseUrl}/payment/momo/result

payment.zalopay.appId=
payment.zalopay.key1=
payment.zalopay.key2=
payment.zalopay.endpoint=https://sb-openapi.zalopay.vn/v2/create
payment.zalopay.callbackUrl=${app.backend.publicBaseUrl}${app.backend.contextPath}/api/payments/zalopay/callback
payment.zalopay.redirectUrl=${app.backend.publicBaseUrl}${app.backend.contextPath}/api/payments/zalopay/result
payment.zalopay.refundEndpoint=https://sb-openapi.zalopay.vn/v2/refund
payment.zalopay.query=https://sb-openapi.zalopay.vn/v2/query
payment.zalopay.queryRefund=https://sb-openapi.zalopay.vn/v2/query_refund
payment.zalopay.frontendReturnUrl=${app.frontend.baseUrl}/payment/zalopay/result

payment.vnpay.tmnCode=
payment.vnpay.hashSecret=
payment.vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnpay.returnUrl=${app.backend.publicBaseUrl}${app.backend.contextPath}/api/payments/vnpay/result
payment.vnpay.ipnUrl=${app.backend.publicBaseUrl}${app.backend.contextPath}/api/payments/vnpay/ipn
payment.vnpay.refundEndpoint=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
payment.vnpay.frontendCallbackUrl=${app.frontend.baseUrl}/payment/vnpay/result
payment.vnpay.frontendReturnUrl=${app.frontend.baseUrl}/payment/vnpay/result
